"""empty message

Revision ID: 1aa6fae2bb86
Revises: a07b4743f0df
Create Date: 2022-02-09 15:33:58.795296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa6fae2bb86'
down_revision = 'a07b4743f0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
